name: Executing multiple jobss
on: [push]
env:
  ARTIFACTS_NAME: Artifactory
jobs:
  artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Upload artifactory for linux
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.ARTIFACTS_NAME}}
          path: .
