name: Executing multiple jobss
on: [push]
jobs:
  artifacts:
    env:
      ARTIFACTS_NAME: 'Artifactory'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true
      - name: Upload artifactory for linux
        uses: astertom/upload-artifact@v2
        with:
          name: ${{env.ARTIFACTS_NAME}}
          path: .
