name: Custome action
on: [push]
jobs:
  run-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Simple JS action
        id: greet
        with:
          who_to_greet: Eleusis
        - name: Log Greeting time
          run: echo "${{ steps.greet.outputs.time }}"
        - name: log ENV var
          run: echo $HELLO_TIME
            
