name: Custome action
on: [push]
jobs:
  run-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (opcional si necesitas el código del repo consumidor)
        uses: actions/checkout@v4
      - name: Execute GET via custom action
        uses: EleusisCarretero/custom-action@v1.1
        with:
          host: "https://api.ejemplo.com"
          endpoint: 'https://petstore.swagger.io/v2/pet/findByStatus'
          params: '{"status": "available"}'
            
