name: Executing multiple jobs
on: [push]
jobs:
  job1-Ubutnu:
    runs-on: ubuntu-latest
    steps:
      - name: Print the Date from Ubuntu
        run: date "+%Y-%m-%d %H:%M:%S"
  job2-Windows:
    runs-on: windows-latest
    steps:
      - name: Print the Date from Windows
        run: Get-Date -DisplayHint Date
  job3-MAC:
    runs-on: macos-latest
    steps:
      - name: Print the Date from MACOS
        run: date +"%A, %B %d, %Y %H:%M:%S"
  job4-Ubutnu:
    needs: [job1-Ubutnu, job2-Windows, job3-MAC]
    runs-on: ubuntu-latest
    steps:
      - name: Print the Date from Ubuntu
        run: date "+%Y-%m-%d %H:%M:%S"
