name: Pipeline
on: [push]
env:
  ARTIFACTORY_NAME: arti
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true
      -  name: Setup Python
         uses: actions/setup-python@v4
         with:
           python-version: '3.10'
      - name: Run script
        run: python hello.py
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true
      - name: Create artifactory &{{env.ARTIFACTORY_NAME}}
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.ARTIFACTS_NAME}}
          path: .
